### PR TITLE
Fixes #57: Improves inheritdoc so that developer documentation is properly referenced on the autogenerated interfaces

### LINKED ISSUE #57: Interfaces are created with "inheritdoc" xml comments
As interfaces are typically at the top of the inheritance chain (interface -> abstract class -> concrete class) inheriting documentation does not make sense.

In manual code, inheritdoc is often used in the concrete class, but since we generate our interface, we put the xml documentation in the class itself. Inheriting bottom up does not work, so if you want to do anything with xml comments at all, I'd suggest you simply copy them.

### PR DESCRIPTION
**Pull request by ChaseFlorell**
based on the comments in #57, by using a `cref` back to the original implementation, we are able to get intellisense working off of autogenerated interfaces.

Resolves #57

### CODE REVIEW

**Comment by simonmckenzie** [comment]
Hi @ChaseFlorell,

There seem to be a lot of whitespace changes - have you run csharpier? Usually the pipeline runs for pull requests and I think you'd have received a lint failure notification - I don't know why it didn't today.

**Comment by ChaseFlorell** [comment]
> Hi @ChaseFlorell,
> 
> There seem to be a lot of whitespace changes - have you run csharpier? Usually the pipeline runs for pull requests and I think you'd have received a lint failure notification - I don't know why it didn't today.

I have not, I'm not sure how to run it TBH. I'll take a look

File: AutomaticInterface/AutomaticInterface/Builder.cs [hunk 1]
```diff
@@ -9,13 +9,13 @@ namespace AutomaticInterface;
 
 public static class Builder
 {
-    private const string InheritDoc = "/// <inheritdoc />"; // we use inherit doc because that should be able to fetch documentation from base classes.
+    private static string InheritDoc(string source) => $"/// <inheritdoc cref=\"{source.Replace('<', '{').Replace('>', '}')}\" />"; // we use inherit doc because that should be able to fetch documentation from base classes.
```
Comment (simonmckenzie) [inline AutomaticInterface/AutomaticInterface/Builder.cs:12]: Might it be tidier if this method took a symbol instead of a string? I feel it would give better type safety and single point of control for conversion of methods/whatever to crefs.

I'm not the owner of this repo or anything, so it's just an idea :)

Comment (ChaseFlorell) [reply AutomaticInterface/AutomaticInterface/Builder.cs:12]: Yep, valid.. I see there is a common `ISymbol` interface that I can pass from all three calls

Comment (ChaseFlorell) [reply AutomaticInterface/AutomaticInterface/Builder.cs]: This is resolved

**Comment by simonmckenzie** [comment]
> > Hi @ChaseFlorell,
> > There seem to be a lot of whitespace changes - have you run csharpier? Usually the pipeline runs for pull requests and I think you'd have received a lint failure notification - I don't know why it didn't today.
> 
> I have not, I'm not sure how to run it TBH. I'll take a look

This is what's in the pipeline - you should be able to run the same locally.

```
dotnet tool restore
dotnet csharpier --check .
```

**Comment by ChaseFlorell** [comment]
> > > Hi @ChaseFlorell,
> > > There seem to be a lot of whitespace changes - have you run csharpier? Usually the pipeline runs for pull requests and I think you'd have received a lint failure notification - I don't know why it didn't today.
> > 
> > 
> > I have not, I'm not sure how to run it TBH. I'll take a look
> 
> This is what's in the pipeline - you should be able to run the same locally.
> 
> ```
> dotnet tool restore
> dotnet csharpier --check .
> ```
> 
> ... I think running without `--check` will format the files in place.

Got it, thanks

**Comment by ChristianSauer** [comment]
For first time contributors, package maintainers (only me currently) have to approve the pipeline run.
Thats due to security concerns (imagine replacing the pipeline with a bitcoin mining script...)

I really like the PR, if you can get it "green" I will merge it asap

**Comment by ChaseFlorell** [comment]
I'm confused because CI reports the following
image

Whereas my local installation of chsharpier shows
image

**Comment by ChaseFlorell** [comment]
> For first time contributors, package maintainers (only me currently) have to approve the pipeline run. Thats due to security concerns (imagine replacing the pipeline with a bitcoin mining script...)
> 
> I really like the PR, if you can get it "green" I will merge it asap

I did push a new version, I'm wondering if you can rerun the pipeline?

**Comment by ChristianSauer** [comment]
I finally had time to merge this. Thanks for your patience!
